# Generated by Django 4.0.1 on 2022-01-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firsstapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='last_modified',
        ),
    ]
